version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000" # Expose port 8000 of the container to port 8000 of the host
      - "8001:8001"

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_database
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: root_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80" # Adjust the port if needed
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
